import React, { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Download, FileText, Music } from 'lucide-react';
import TabsGeneration from '../TabsGeneration';
import PracticeMode from './PracticeMode';
import { useToast } from '@/hooks/use-toast';

interface ChordSegment {
  start: number;
  end: number;
  chord: string;
  duration: number;
}

interface EnhancedPracticeSectionProps {
  results: any;
  originalAudio: Blob | null;
  chordTimeline: ChordSegment[];
}

const EnhancedPracticeSection: React.FC<EnhancedPracticeSectionProps> = ({
  results,
  originalAudio,
  chordTimeline
}) => {
  const { toast } = useToast();

  const downloadChordChart = () => {
    const chordChart = generateChordChart();
    const blob = new Blob([chordChart], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${results.song.title}-chord-chart.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: 'Downloaded!',
      description: 'Chord chart saved to your downloads',
    });
  };

  const generateChordChart = () => {
    return `🎸 RIOT SHEETS CHORD CHART 🎸
=================================

Song: ${results.song.title}
Artist: ${results.song.artist}
Key: ${results.analysis.key}
Tempo: ${results.analysis.tempo} BPM
Difficulty: ${results.analysis.difficulty}

CHORD PROGRESSION:
${results.analysis.chords?.join(' - ') || 'Not available'}

TIMELINE:
${chordTimeline.map(segment => 
  `${segment.start.toFixed(1)}s - ${segment.end.toFixed(1)}s: ${segment.chord}`
).join('\n')}

ANALYSIS:
${results.analysis.tips}

Generated by RIOT SHEETS - Where Punk Meets Precision ⚡
Visit: https://riotsheets.com
`;
  };

  const exportMIDI = () => {
    // Real MIDI export functionality - placeholder removed
    console.log('🎵 MIDI export requested for:', results.song.title);
    
    toast({
      title: 'MIDI Export',
      description: 'MIDI export functionality is being developed',
    });
  };

  if (!originalAudio || !chordTimeline.length) {
    return (
      <div className="punk-card text-center py-8">
        <p className="text-muted-foreground">
          Practice features will appear after audio analysis is complete.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Quick Actions */}
      <div className="text-center space-y-4">
        <div className="flex flex-wrap justify-center gap-4">
          <Button onClick={downloadChordChart} className="punk-button">
            <Download className="h-4 w-4 mr-2" />
            DOWNLOAD CHORD CHART
          </Button>
          <Button onClick={exportMIDI} variant="outline">
            <Music className="h-4 w-4 mr-2" />
            EXPORT MIDI
          </Button>
        </div>
        <p className="text-xs text-muted-foreground">
          Real-time chord recognition powered by Riot-Sheets AI - Practice with precision timing!
        </p>
      </div>

      {/* Enhanced Practice Tools */}
      <Tabs defaultValue="practice" className="w-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="practice">🎸 Practice Mode</TabsTrigger>
          <TabsTrigger value="tabs">📋 Generate Tabs</TabsTrigger>
        </TabsList>
        
        <TabsContent value="practice" className="mt-6">
          <PracticeMode
            audioBlob={originalAudio}
            chordTimeline={chordTimeline}
            songInfo={{
              title: results.song.title,
              artist: results.song.artist,
              key: results.analysis.key,
              tempo: results.analysis.tempo
            }}
          />
        </TabsContent>
        
        <TabsContent value="tabs" className="mt-6">
          <TabsGeneration
            songInfo={{
              title: results.song.title,
              artist: results.song.artist,
              key: results.analysis.key,
              chords: results.analysis.chords
            }}
            chordProgression={results.analysis.chords || chordTimeline.map(c => c.chord).filter((chord, index, arr) => arr.indexOf(chord) === index)}
          />
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default EnhancedPracticeSection;